export default function Terms() {
  return (
    <main className="min-h-screen bg-white flex flex-col items-center p-6">
      <div className="w-full max-w-md py-12">
        <h1 className="text-2xl font-semibold text-gray-900 mb-2">Terms of Use</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: April 2026</p>

        <div className="space-y-6 text-sm text-gray-600 leading-relaxed">
          <section>
            <h2 className="font-medium text-gray-900 mb-2">Use of the service</h2>
            <p>Stylesmith is a free tool that provides AI-generated outfit suggestions for informational and inspirational purposes only. By using Stylesmith you agree to these terms.</p>
          </section>

          <section>
            <h2 className="font-medium text-gray-900 mb-2">No professional advice</h2>
            <p>Stylesmith is not a licensed styling service. Outfit recommendations are generated by AI and should be treated as suggestions only. We make no guarantees about the suitability of any recommendation.</p>
          </section>

          <section>
            <h2 className="font-medium text-gray-900 mb-2">Affiliate disclaimer</h2>
            <p>Stylesmith participates in affiliate programs. We may earn commissions from purchases made through links on our site. This does not affect the price you pay.</p>
          </section>

          <section>
            <h2 className="font-medium text-gray-900 mb-2">Limitation of liability</h2>
            <p>Stylesmith is provided as-is without warranties of any kind. We are not liable for any purchases made based on our recommendations.</p>
          </section>

          <section>
            <h2 className="font-medium text-gray-900 mb-2">Changes to these terms</h2>
            <p>We may update these terms at any time. Continued use of Stylesmith after changes means you accept the updated terms.</p>
          </section>
        </div>

        <a href="/" className="inline-block mt-10 text-sm text-gray-400 underline hover:text-gray-600">
          Back to Stylesmith
        </a>
      </div>
    </main>
  );
}